replicaCount: 1

image:
  repository: elumole22/mcp-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}

labels:
  app: mcp-server

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: mcp-server.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
